/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TransferContract } from "./TransferContract";

export { TransferContract__factory } from "./factories/TransferContract__factory";
